Repository drofp/MyRPS, pull requests merged in 2019-04, with the labels that each got.

#43 Iss 42
  Makefile
  include/chooser.h
  include/computer_player.h
  include/game.h
  include/ml_chooser.h
  include/move.h
  include/move_choice.h
  include/my_rps.h
  include/random_chooser.h
  include/rps_frame.h
  include/rps_panel.h
  include/start_menu.h
  src/comupter_player.cpp
  src/game.cpp
  src/main.cpp
  src/ml_chooser.cpp
  src/move_choice.cpp
  src/my_rps.cpp
  src/random_chooser.cpp
  src/rps_frame.cpp
  src/rps_panel.cpp
Labels: enhancement

#47 Iss 45
  include/chooser.h
  include/computer_player.h
  include/game.h
  include/game_frame.h
  include/game_panel.h
  include/ml_chooser.h
  include/random_chooser.h
  src/comupter_player.cpp
  src/game.cpp
  src/game_frame.cpp
  src/game_panel.cpp
  src/ml_chooser.cpp
  src/my_rps.cpp
  src/random_chooser.cpp
Labels: enhancement

#52 Added Multipanel GUI for EveryReceipt
  include/game_panel.h
  include/setting_option.h
  src/game_panel.cpp
  src/my_rps.cpp
  src/setting_option.cpp
Labels: enhancement

#54 Fixed randomizer issue
  include/move_choice.h
  src/random_chooser.cpp
Labels: bug

#55 Added Round Choice to MyRPS GUI
  include/game_panel.h
  src/game_frame.cpp
  src/game_panel.cpp
  src/my_rps.cpp
Labels: enhancement

#58 Iss 57
  include/game.h
  include/game_frame.h
  include/game_panel.h
  include/rps_frame.h
  include/rps_panel.h
  include/start_menu_frame.h
  include/start_menu_panel.h
  src/game.cpp
  src/game_frame.cpp
  src/game_panel.cpp
  src/my_rps.cpp
  src/rps_frame.cpp
  src/rps_panel.cpp
  src/settings_menu.cpp
  src/start_menu.cpp
  src/start_menu_frame.cpp
  src/start_menu_panel.cpp
  src/start_option.cpp
Labels: cleanup
